# Generated by Django 5.0.2 on 2024-03-07 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_user_date_of_birth'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagementProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_management_profile',
                'managed': False,
            },
        ),
    ]
