# Generated by Django 5.0.2 on 2024-03-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_bio_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='memberid',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
    ]
