# Generated by Django 5.0.2 on 2024-03-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_image_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='Untitled Image', max_length=200),
        ),
    ]
