# Generated by Django 5.0.2 on 2024-03-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_alter_profile_options_remove_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
