# Generated by Django 5.0.2 on 2024-03-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_profile_options_remove_profile_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
