# Generated by Django 5.0.2 on 2024-03-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_customuser_background_image_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
