# Generated by Django 5.0.2 on 2024-03-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_profile_date_joined_profile_email_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
