# Generated by Django 5.0.2 on 2024-03-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_remove_profile_date_joined_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
